var errors = require('./errors');

var mappedSDErrors = {
    // Authentication and Authorization errors (10 - 19)
    10: errors["AuthMissingHeaderError"],
    11: errors["AuthAPIKeyError"],
    12: errors["AuthInvalidAPIKeyError"],
    13: errors["AuthIncorrectPermissionError"],
    14: errors["AuthInvalidRemoteAddrError"],
    15: errors["CustomkeyInvalidColumnCreationError"],
    16: errors["CustomKeyInvalidPermissionForColumnError"],
    17: errors["CustomKeyInvalidOperationError"],
    18: errors["CustomKeyNotPermittedError"],
    19: errors["CustomKeyRouteNotPermittedError"],
    20: errors["DemoApiInvalidEndpointError"],
    // Request validations (21 - 29)
    21: errors["RequestMissingContentTypeError"],
    22: errors["RequestIncorrectContentTypeValueError"],
    23: errors["RequestRateLimitError"],
    24: errors["RequestInvalidJsonError"],
    25: errors["RequestInvalidHttpMethodError"],
    26: errors["RequestInvalidEndpointError"],
    27: errors["RequestIncorrectHttpError"],
    28: errors["RequestExceedLimitError"],
    // Account Errors (30 - 39)
    30: errors["AccountMissingPaymentMethodError"],
    31: errors["AccountPaymentRequiredError"],
    32: errors["AccountBannedError"],
    33: errors["AccountDisabledError"],
    39: errors["InsertInvalidRangeException"],
    // Column errors (40 - 59)
    40: errors["ColumnMissingParamError"],
    41: errors["ColumnTypeError"],
    42: errors["ColumnIntegerValuesError"],
    43: errors["ColumnAlreadyExistsError"],
    44: errors["ColumnLimitError"],
    45: errors["ColumnTimeSeriesLimitError"],
    46: errors["ColumnTimeSeriesSystemLimitError"],
    47: errors["ColumnDecimalTypeError"],
    48: errors["ColumnStorageValueError"],
    49: errors["ColumnInvalidApiNameError"],
    50: errors["ColumnInvalidNameError"],
    51: errors["ColumnInvalidDescriptionError"],
    52: errors["ColumnExceedDescriptionlengthError"],
    53: errors["ColumnInvalidCardinalityError"],
    54: errors["ColumnDecimalLimitError"],
    55: errors["ColumnRangeLimitError"],
    56: errors["ColumnExceededMaxNameLenghtError"],
    57: errors["ColumnExceededMaxApiNameLenghtError"],
    58: errors["ColumnEmptyEntityIdError"],
    59: errors["ColumnExceededPermitedValueError"],
    // Insert errors (60 - 79)
    60: errors["InsertInvalidDecimalPlacesError"],
    61: errors["InsertEntityValueTypeError"],
    62: errors["InsertColumnNameTypeError"],
    63: errors["InsertColumnTypeError"],
    64: errors["InsertEntityNameTooBigError"],
    65: errors["InsertColumnValueTooBigError"],
    66: errors["InsertTimeSeriesDateFormatError"],
    67: errors["InsertColumnNotActiveError"],
    68: errors["InsertIdLimitError"],
    69: errors["InsertColumnLimitError"],
    70: errors["InsertDateFormatError"],
    71: errors["InsertColumnStringEmptyValueError"],
    72: errors["InsertColumnTimeseriesInvalidParameterError"],
    73: errors["InsertColumnNumericInvalidValueError"],
    74: errors["InsertColumnTimeseriesMissingValueError"],
    75: errors["QueryTimeSeriesInvalidPrecisionSecondsError"],
    76: errors["QueryTimeSeriesInvalidPrecisionMinutesError"],
    77: errors["QueryTimeSeriesInvalidPrecisionHoursError"],
    78: errors["QueryDateFormatError"],
    79: errors["QueryRelativeIntervalError"],
    // Query errors (80 - 109)
    80: errors["QueryMissingQueryError"],
    81: errors["QueryInvalidTypeError"],
    82: errors["QueryMissingTypeParamError"],
    83: errors["QueryInvalidOperatorError"],
    84: errors["QueryIncorrectOperatorUsageError"],
    85: errors["QueryColumnNotActiveError"],
    86: errors["QueryMissingOperatorError"],
    87: errors["QueryIncompleteError"],
    88: errors["QueryEventCountQueryError"],
    89: errors["QueryInvalidMetricError"],
    90: errors["QueryIntegerError"],
    91: errors["QueryColumnLimitError"],
    92: errors["QueryLevelLimitError"],
    93: errors["QueryBadAggsFormationError"],
    94: errors["QueryInvalidFilterValueError"],
    95: errors["QueryMetricsLevelError"],
    96: errors["QueryTimeSeriesError"],
    97: errors["QueryMetricsTypeError"],
    98: errors["QueryContainsNumericError"],
    99: errors["QueryExistsEntityLimitError"],
    100: errors["QueryMultipleFiltersError"],
    102: errors["QueryMissingNameParamError"],
    103: errors["QuerySavedAlreadyExistsError"],
    104: errors["QuerySavedNotExistsError"],
    105: errors["QuerySavedInvalidTypeError"],
    106: errors["MethodNotAllowedError"],
    107: errors["QueryExistsMissingIdsError"],
    108: errors["QueryInvalidFormatError"],
    109: errors["QueryTopValuesParameterEmptyError"],
    110: errors["QueryDataExtractionLimitValueError"],
    111: errors["QueryDataExtractionLimitValueTooBigError"],
    112: errors["QueryDataExtractionLimitAndPageTokenValueError"],
    113: errors["QueryDataExtractionPageTokenValueError"],
    114: errors["QueryDataExtractionColumnLimitError"],
    115: errors["QueryExistsEntityEmptyError"],
    116: errors["QuerySavedInvalidQueryValueError"],
    117: errors["QuerySavedInvalidCachePeriodValueError"],
    118: errors["QuerySavedInvalidNameError"],
    119: errors["QueryCountInvalidParameterError"],
    120: errors["QueryAggregationInvalidParameterError"],
    121: errors["QueryAggregationInvalidFilterQueryError"],
    122: errors["QueryInvalidMinfreqError"],
    123: errors["QueryExceededMaxNumberQuerysError"],
    124: errors["QueryInvalidOperatorUsageError"],
    125: errors["QueryInvalidParameterUsageError"],
    126: errors["QueryParameterInvalidColumnUsageError"],
    127: errors["QueryInvalidColumnUsageError"],
    // Internal errors (110 - 120)
    130: errors["InternalError"],
    131: errors["ColumnCreateInternalError"],
}

module.exports = mappedSDErrors;
