var errors = require('./errors');

var mappedSDErrors = {
    // Authentication and Authorization errors (10 - 19)
    10: errors["AuthMissingHeaderError"],
    11: errors["AuthAPIKeyError"],
    12: errors["AuthInvalidAPIKeyError"],
    13: errors["AuthIncorrectPermissionError"],
    14: errors["AuthInvalidRemoteAddrError"],
    15: errors["CustomkeyInvalidFieldCreationError"],
    16: errors["CustomKeyInvalidPermissionForFieldError"],
    17: errors["CustomKeyInvalidOperationError"],
    18: errors["CustomKeyNotPermittedError"],
    19: errors["CustomKeyRouteNotPermittedError"],
    20: errors["DemoApiInvalidEndpointError"],
    // Request validations (21 - 29)
    21: errors["RequestMissingContentTypeError"],
    22: errors["RequestIncorrectContentTypeValueError"],
    23: errors["RequestRateLimitError"],
    24: errors["RequestInvalidJsonError"],
    25: errors["RequestInvalidHttpMethodError"],
    26: errors["RequestInvalidEndpointError"],
    27: errors["RequestIncorrectHttpError"],
    28: errors["RequestExceedLimitError"],
    // Account Errors (30 - 39)
    30: errors["AccountMissingPaymentMethodError"],
    31: errors["AccountPaymentRequiredError"],
    32: errors["AccountBannedError"],
    33: errors["AccountDisabledError"],
    39: errors["IndexInvalidRangeException"],
    // Field errors (40 - 59)
    40: errors["FieldMissingParamError"],
    41: errors["FieldTypeError"],
    42: errors["FieldIntegerValuesError"],
    43: errors["FieldAlreadyExistsError"],
    44: errors["FieldLimitError"],
    45: errors["FieldTimeSeriesLimitError"],
    46: errors["FieldTimeSeriesSystemLimitError"],
    47: errors["FieldDecimalTypeError"],
    48: errors["FieldStorageValueError"],
    49: errors["FieldInvalidApiNameError"],
    50: errors["FieldInvalidNameError"],
    51: errors["FieldInvalidDescriptionError"],
    52: errors["FieldExceedDescriptionlengthError"],
    53: errors["FieldInvalidCardinalityError"],
    54: errors["FieldDecimalLimitError"],
    55: errors["FieldRangeLimitError"],
    56: errors["FieldExceededMaxNameLenghtError"],
    57: errors["FieldExceededMaxApiNameLenghtError"],
    58: errors["FieldEmptyEntityIdError"],
    59: errors["FieldExceededPermitedValueError"],
    // Index errors (60 - 79)
    60: errors["IndexInvalidDecimalPlacesError"],
    61: errors["IndexEntityValueTypeError"],
    62: errors["IndexFieldNameTypeError"],
    63: errors["IndexFieldTypeError"],
    64: errors["IndexEntityNameTooBigError"],
    65: errors["IndexFieldValueTooBigError"],
    66: errors["IndexTimeSeriesDateFormatError"],
    67: errors["IndexFieldNotActiveError"],
    68: errors["IndexIdLimitError"],
    69: errors["IndexFieldLimitError"],
    70: errors["IndexDateFormatError"],
    71: errors["IndexFieldStringEmptyValueError"],
    72: errors["IndexFieldTimeseriesInvalidParameterError"],
    73: errors["IndexFieldNumericInvalidValueError"],
    74: errors["IndexFieldTimeseriesMissingValueError"],
    75: errors["QueryTimeSeriesInvalidPrecisionSecondsError"],
    76: errors["QueryTimeSeriesInvalidPrecisionMinutesError"],
    77: errors["QueryTimeSeriesInvalidPrecisionHoursError"],
    78: errors["QueryDateFormatError"],
    79: errors["QueryRelativeIntervalError"],
    // Query errors (80 - 109)
    80: errors["QueryMissingQueryError"],
    81: errors["QueryInvalidTypeError"],
    82: errors["QueryMissingTypeParamError"],
    83: errors["QueryInvalidOperatorError"],
    84: errors["QueryIncorrectOperatorUsageError"],
    85: errors["QueryFieldNotActiveError"],
    86: errors["QueryMissingOperatorError"],
    87: errors["QueryIncompleteError"],
    88: errors["QueryEventCountQueryError"],
    89: errors["QueryInvalidMetricError"],
    90: errors["QueryIntegerError"],
    91: errors["QueryFieldLimitError"],
    92: errors["QueryLevelLimitError"],
    93: errors["QueryBadAggsFormationError"],
    94: errors["QueryInvalidFilterValueError"],
    95: errors["QueryMetricsLevelError"],
    96: errors["QueryTimeSeriesError"],
    97: errors["QueryMetricsTypeError"],
    98: errors["QueryContainsNumericError"],
    99: errors["QueryExistsEntityLimitError"],
    100: errors["QueryMultipleFiltersError"],
    102: errors["QueryMissingNameParamError"],
    103: errors["QuerySavedAlreadyExistsError"],
    104: errors["QuerySavedNotExistsError"],
    105: errors["QuerySavedInvalidTypeError"],
    106: errors["MethodNotAllowedError"],
    107: errors["QueryExistsMissingIdsError"],
    108: errors["QueryInvalidFormatError"],
    109: errors["QueryTopValuesParameterEmptyError"],
    110: errors["QueryDataExtractionLimitValueError"],
    111: errors["QueryDataExtractionLimitValueTooBigError"],
    112: errors["QueryDataExtractionLimitAndPageTokenValueError"],
    113: errors["QueryDataExtractionPageTokenValueError"],
    114: errors["QueryDataExtractionFieldLimitError"],
    115: errors["QueryExistsEntityEmptyError"],
    116: errors["QuerySavedInvalidQueryValueError"],
    117: errors["QuerySavedInvalidCachePeriodValueError"],
    118: errors["QuerySavedInvalidNameError"],
    119: errors["QueryCountInvalidParameterError"],
    120: errors["QueryAggregationInvalidParameterError"],
    121: errors["QueryAggregationInvalidFilterQueryError"],
    122: errors["QueryInvalidMinfreqError"],
    123: errors["QueryExceededMaxNumberQuerysError"],
    124: errors["QueryInvalidOperatorUsageError"],
    125: errors["QueryInvalidParameterUsageError"],
    126: errors["QueryParameterInvalidFieldUsageError"],
    127: errors["QueryInvalidFieldUsageError"],
    // Internal errors (110 - 120)
    130: errors["InternalError"],
    131: errors["FieldCreateInternalError"],
}

module.exports = mappedSDErrors;
